---
driver:
  name: lxd_cli

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ansible_yum_repo: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
#  require_chef_omnibus: false
  require_ansible_omnibus: true
#  require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7
#  - name: alpine-3.4
## precise & centos-6 not supported: kitchen and many plugins requires ruby >= 2.0
#  - name: centos-6
#  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
    attributes:
  - name: user
    run_list:
    attributes:
    provisioner:
      name: ansible_playbook
      hosts: test-kitchen-user
      playbook: test/integration/user/user.yml
